### PR TITLE
Patch for kml.fmt

### PR DESCRIPTION
**Pull request by fedorkotov**
I updated kml.fmt. 
- Limited image preview size to 500px. Resolution of images from modern cameras is often too large to fit on screen.
- Changed xlmns to match KML written by Google Earth.
- Removed unnecessary table from placemark description.

### CODE REVIEW

**Comment by boardhead** [comment]
It is reasonable to limit the size to 500px, but I don't know about the namespace changes:

1. you define "gx", "kml" and "atom" namespaces, but don't use any of these in the XML.

2. Was there are a problem with the original xmlns?  At one time this is what google earth used, so one would expect systems to be backward compatible for this namespace.

Also, you have removed the table I was using to hold the image.  I can't remember why I was doing this, but presumably I had a reason.  Was this causing problems for you?

**Comment by fedorkotov** [comment]
I had no problems with the original `xmlns="http://earth.google.com/kml/2.0"` and I do not insist on changing it. I'm no expert on KML format.
Both GIS tools I use (Google Earth Pro 7.3.2.5776 and GDAL) write KML files with `xmlns="http://www.opengis.net/kml/2.2"`. 
`gx`, `kml` and `atom` namespaces are not required for this exiftool format file. I just copy-pasted the line from KML exported by Google Earth. I probably shouldn't have. I'll remove them.

I removed table because I think photo popup in Google Earth looks nicer without extra space
with-and-without-table
If you think the table is there for a good reason, I'll return it back.

I also removed empty `<Snippet/>` element. According to Google's [KML Reference ](https://developers.google.com/kml/documentation/kmlreference) it's absence shouldn't change anything as long as `<description>` does not contain any text.  I compared KML files with and without it in Google Earth and they seem to look be identical.

I also noticed that portrait images are too large even with `style="max-width:500px;"` I'll change style to `max-width:500px;max-height:500px;`

**Comment by boardhead** [comment]
OK, thanks.  That looks good.  I'll try this out and merge it if everything goes well at the end of the month when I get back from vacation.

**Comment by boardhead** [comment]
This patch was included in ExifTool 11.85 f0429f9005073cdfe7bb901b1d5f02f740aee892

**Pull request closed without merging**
