### PR TITLE
Add support for Windows paths longer than 260 characters on supported Windows versions

### PR DESCRIPTION
**Pull request by dqhieuu**
- This commits tries to use `openL` and `testL` from `Win32::LongPath` as a drop-in replacement for Perl's native `open` and file test `-t` if possible.
- All tests have passed on my Windows 11 machine with long path enabled. We could probably add some tests for this, which should be ignore if any of this isn't true:
  - Is not running on Windows
  - Windows version doesn't [support long file path](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation)
  - Registry value `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled` is not set to `DWORD 1`

This would fix the issues mentioned in https://exiftool.org/forum/index.php?topic=15095.0 and related threads.

### CODE REVIEW

**Comment by boardhead** [comment]
Thanks for this patch.  However, the problem is much bigger than this.  ExifTool doesn't just open files, so patching only -e and openL is a partial solution.  ExifTool also scans directories (readdir), creates directories (mkdir), deletes files (unlink), renames files (rename), and reads file status (stat).

Also, this patch won't work for Windows files with Unicode characters as it bypasses the existing patch for these.

Man, Windows file handling is really a complete mess.  :(

- Phil

**Comment by boardhead** [comment]
Actually, it looks like this probably does handle Unicode characters, but I can't see what system i/o routines are being used by this module.  Maybe it is possible that ExifTool already handles long path names if you add "-charset UTF8 -api windowswidefile" to the command -- could you test this?

- Phil

**Comment by dqhieuu** [comment]
Hi Phil,

> Thanks for this patch. However, the problem is much bigger than this. ExifTool doesn't just open files, so patching only -e and openL is a partial solution. ExifTool also scans directories (readdir), creates directories (mkdir), deletes files (unlink), renames files (rename), and reads file status (stat).

> Also, this patch won't work for Windows files with Unicode characters as it bypasses the existing patch for these.
 
Thank you for the information. If possible, I would like patch these native functions with wrapper functions, as it has been 6 years since Windows introduced the long path option, and Perl probably doesn't intend to support that.

> Actually, it looks like this probably does handle Unicode characters, but I can't see what system i/o routines are being used by this module. Maybe it is possible that ExifTool already handles long path names if you add "-charset UTF8 -api windowswidefile" to the command -- could you test this?
> 
> * Phil

I believe you meant `-charset filename=UTF8 -api WindowsWideFile`. Nevertheless, adding the arguments didn't work, unfortunately. I have tested some cases with these arguments and found possible bugs in the current code:
<details>
  <summary>Results</summary>

- `exiftool' -charset filename=UTF8 'G:\testfile\ÂFCP - Copy.jpg'` and `exiftool' -charset filename=UTF8 -api WindowsWideFile 'G:\testfile\ÂFCP - Copy.jpg'` : Doesn't work and ExifTool thinks the encoding is incorrect. Log:
```
Invalid filename encoding for G:/testfile/┬FCP - Copy.jpg
Error opening directory G:/testfile/┬FCP - Copy.jpg
```
(The output log seems to have an encoding error, but actually it's just Perl outputting incorrectly to the Windows console. Printing Unicode text to files is completely okay.)
- `exiftool -api WindowsWideFile 'G:\testfile\ÂFCP - Copy.jpg'` and `exiftool 'G:\testfile\ÂFCP - Copy.jpg'` : Both are able to read the file and output the metadata. A warning saying `FileName encoding not specified` is displayed.

- Long path with non-ASCII: `perl 'G:\testfile\verylângpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder\rylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder - Copy\AFCP.jpg'`: all 4 argument combinations: return `Error: File not found - G:/testfile/verylΓngpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder/rylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder - Copy/AFCP.jpg`

- Long path with only ASCII: `perl 'G:\testfile\verylângpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder\rylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder - Copy\AFCP.jpg'`: all 4 argument combinations also return `Error: File not found - G:/testfile/verylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder/rylongpathfolderverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathverylongpathfolder - Copy/AFCP.jpg`
</details>

Digging more into the code, I found both [Win32API::File](https://metacpan.org/release/CHORNY/Win32API-File-0.1203/source/File.xs) and [Win32::LongPath](https://metacpan.org/release/RBOISVERT/Win32-LongPath-2.2/source/xs/LongPath.xs) use Windows' `CreateFileW` internally (which [supports long path](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#:~:text=no%20longer%20have%20MAX_PATH%20restrictions%20if%20you%20opt%2Din%20to%20long%20path%20behavior%3A%20CopyFileW%2C%20CopyFile2%2C%20CopyFileExW%2C%20CreateFileW)), with virtually the same arguments. But calling `Win32API::File::CreateFileW` failed to retrieve a file descriptor for files with long paths, while `Win32::LongPath::openL` didn't. I guess there's some differences in the Perl code to encode the long path and pass to the Windows function.

Hieu

**Comment by boardhead** [comment]
Hi Hieu,

I would be happier to accept a patch that would fix the current Win32API::File::CreateFileW call if you can figure it out.  I want to avoid having to use Wind32::LongPath.

- Phil

**Comment by dqhieuu** [comment]
> Hi Hieu,
> 
> I would be happier to accept a patch that would fix the current Win32API::File::CreateFileW call if you can figure it out. I want to avoid having to use Wind32::LongPath.
> 
> * Phil

It seems like Windows' system call support for long paths is an absolute mess, but I've finally got the hang of it. The input long path needs to be normalized, with some pretty strict requirements:
- Path must be prefixed with `\\?\`. So `C:\exiftool` becomes `\\?\C:\exiftool`.
- `\` and `/` delimiters are sensitive. As a result, `/` must be all changed to `\`
-  When using long path, wildcards such as `*` and `?` aren't supported and Windows methods will throw a warning or treat them as literal.
- Path must be absolute, thus must not contain `../` and `./`
- And as usual, passing non-ASCII chars that aren't UTF16-LE are fked.

So I've added a path normalization function that can convert a Windows path to a conforming absolute long path, and removed the Win32::LongPath dependency.

Additionally, I fixed Unicode path scanning and recursion on Windows by encoding the output from `Win32::FindFile::ReadDir` to UTF-8 with `Encode::decode('utf8')`. (Is currently working on my machine. Before `exiftool -charset filename=UTF8 -api WindowsWideFile -r .` didn't work when the scanner found a non-ascii file name)

There's a limitation is that even after this fix, if we run ExifTool for a folder (could be with -r), it will not find anything if the input path exceeds Windows 256 char limit. This is because `Win32::FindFile::ReadDir` doesn't support long path inputs or relative paths which eventually reach a long path (whatever method, it all points to the same system call that needs an absolute long path). This dependency's last update is in 2014 so I believe we should replace it with something else.

**Comment by boardhead** [comment]
Thanks, this sounds promising.  I won't be able to look into the details for at least a few days, and any patch will have to wait until after production version 13.00 is released in a couple of weeks, but I appreciate your effort on this.

- Phil

**Comment by boardhead** [comment]
I've just released ExifTool 13.01 with this functionality enabled via the API WindowsLongPath option.  Please test things.  My tests were successful for reading files with long paths, but it still needs lots more testing.

**Comment by boardhead** [comment]
We have found 3 problems so far that resulted in "file not found" errors.  These will be addressed in 13.02:

1. UNC paths (starting with "\\server\share\PATH")

2. Relative paths on the current drive (starting with "\PATH\")

3. Absolute paths on another drive (starting with "x:PATH\")

**Comment by dqhieuu** [comment]
Thanks, Phil. I've read the thread and really appreciate your efforts to test this out!

Previously, I also considered using long paths only when reaching the limit, but since this syntax [dates back to the DOS era](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths), I just took that it could work on most Windows versions and decided that it was better to always have a long-path compliant path. But playing it safe is also a valid point, I agree.

Hieu

**Comment by boardhead** [comment]
After fixing a few problems, this feature has been implemented

**Pull request closed without merging**
