### PR TITLE
Improve lens detection for Composite::LensID

### PR DESCRIPTION
**Pull request by mattsta**
Hey Phil,

Thanks for your quick review of my Nikon lens fix.

Here's another fun one I ran into during a mass photo import.

EXIF `Composite::LensID` has a strict requirement on `LensType`, but iPhone files don't seem to populate `LensType`—it only gives me `LensModel`.

This patch removes the strict requirement on `LensType`. Now `LensModel` can populate `Composite::LensID` too.

Images used for testing:
- Panasonic: [regular LensType, proper Composite::LensID extracted](https://matt.sh/files/exif-test/panasonic.jpg) — works correctly before and after this patch
- iPhone: [no LensType, only LensModel, so Composite::LensID wasn't being populated](https://matt.sh/files/exif-test/iphone6plus.jpg) — only works correctly after this patch

The improvement also unexpectedly broke `make test` (but in a good way). Now we're extracting more information from `PhaseOne` test image as well, so the text compare doesn't line up anymore:
```haskell
t/PhaseOne.t ....... 1/3
  Test 2 differs beginning at line 95:
    Test gave: "[Composite, Composite, Camera] Exif::LensID - Lens ID: Mamiya LS 80mm f/2.8 D"
    Should be: "[Composite, Composite, Image] Exif::Megapixels - Megapixels: 40.1"

  Test 3 differs beginning at line 168:
    Test gave: "[Composite, Composite, Camera] Exif::LensID - Lens ID: Mamiya LS 80mm f/2.8 D"
    Should be: "[Composite, Composite, Image] Exif::LightValue - Light Value: 15.3"
t/PhaseOne.t ....... Failed 2/3 subtests
```

I think that's all for this attempt! I'll be back if I see more instances of `Composite` trying to be not-Composite by not back-populating existing values as expected.

### CODE REVIEW

**Comment by boardhead** [comment]
This looks good.  Thanks.  This patch will appear in version 12.00

**Comment by boardhead** [comment]
Hmmm.  This patch had a negative effect for some lenses:

https://exiftool.org/forum/index.php?topic=12098.0

Before - Lens ID: Minolta/Sony AF 75-300mm F4.5-5.6 (D)
After    - Lens ID: 75-300mm F4.5-5.6

for this sample:

2021-01-18-07-27-01-1800x1200

Before - Lens ID: Minolta/Sony AF 75-300mm F4.5-5.6 (D)
After    - Lens ID: 75-300mm F4.5-5.6

for this sample:

7005073861_bc154bf9f3_o

**Comment by mattsta** [comment]
Hmm... so this all pivots around the `Require => 'LensType'` condition.

Looks like there's either:
- more magic variables need to be printed in the `ValueConv` and/or `PrintConv` sections, but I can't figure out how to extract the underling correct values properly.
- or perhaps the `RawConv` condition is now too specific (or `ValueConv` needs additional values) and valid conditions are being excluded?

If I re-add the require line, the Minolta/Sony tags show up (because they have 'LensType'), but then iPhone lenses don't show up.

Also found a third condition where a Panasonic camera doesn't populate composite LensID with or without the change, but it does have a valid full `Lens` that should be just copied over to composite with no changes.

iPhone photo with no composite LensId if `LensType` is required:
cars-smaller

iPhone photo reports *with* `Require => 'LensType'`:
```haskell
% ./exiftool cars-smaller.jpg |grep Lens
Lens Info                       : 4.25-6mm f/1.8-2.4
Lens Make                       : Apple
Lens Model                      : iPhone XS Max back dual camera 4.25mm f/1.8
```

iPhone photo reports *without* `Require => 'LensType'`:
```haskell
% ./exiftool cars-smaller.jpg |grep Lens
Lens Info                       : 4.25-6mm f/1.8-2.4
Lens Make                       : Apple
Lens Model                      : iPhone XS Max back dual camera 4.25mm f/1.8
Lens ID                         : iPhone XS Max back dual camera 4.25mm f/1.8
```


Panasonic photo with no composite LensId either before or after the change:
P1010177-smaller

Panasonic photo reports the same output with or without `Require => 'LensType'`:

```haskell
% ./exiftool P1010177-smaller.jpg |grep Lens
Lens                            : LUMIX G 14/F2.5
Lens Serial Number              : 01JG6061760R
```

**Comment by mattsta** [comment]
oh, just saw Linas's comparison output too. Well that's a big mess of a change then. More lenses are now detected, but it broke the formatting for tons of existing lenses.

Not sure how to repair the composite lens id formatting at this juncture without a refactor to make the logic flow somewhat simpler. Seems like a game of wack-a-lens where fixing one edge case breaks other established cases.

**Comment by linaspasv** [comment]
@mattsta maybe the scope for new rules should be limited to particular brands only or if the original LensID is empty to look for some extra fields?

Another idea is to leave LensID field as it was intended before and maybe create LensIDExtra field and let the developers decide what field to use for now.

There are couple of really good examples where this change is beneficial.

```
[#1167 - explorecams] https://cdn.explorecams.com/storage/test/explorecams-1167.jpg
[ExifTool 11.99] LensID: 
[ExifTool 12.16] LensID: iPhone 6s back camera 4.15mm f/2.2
```

```
[#1335 - explorecams] https://cdn.explorecams.com/storage/test/explorecams-1335.jpg
[ExifTool 11.99] LensID: 
[ExifTool 12.16] LensID: Sony FE 600 mm F4 GM OSS (SEL600F40GM) + 1.4X Teleconverter (SEL14TC)
```

```
[#1351 - explorecams] https://cdn.explorecams.com/storage/test/explorecams-1351.jpg
[ExifTool 11.99] LensID: Sigma 14-24mm f/2.8 DG HSM | A + 1.4x or Sigma 14-24mm f/2.8 DG HSM + 1.4x
[ExifTool 12.16] LensID: Sigma 20mm f/1.4 DG HSM | A
```

**Comment by mattsta** [comment]
> maybe the scope for new rules should be limited to particular brands only or if the original LensID is empty to look for some extra fields?

Great idea in theory, but it seems with `Require => 'LensType'`, exiftool is pre-processing or custom-formatting the result somehow that we can't reproduce when we remove the requirement. With the single requirement in place, LenID lenses are good and non-LensID lenses don't show up. With the requirement gone, non-LensID lenses show up, but it breaks many LensID lenses (but not all of them!)

> Another idea is to leave LensID field as it was intended before and maybe create LensIDExtra field and let the developers decide what field to use for now.

Another great idea, but LensID is being populated _before_ we reach the formatting step, so it may require a deeper dive into the guts of exiftool to refactor some parsing decisions.

There's some magic pre-processing or variable substituion happening before we reach the composite lens ID generation phase I wasn't able to track down where LensID creates a well formatted composite seemingly external to the formatting step itself, and if we remove the requirement, we also forfeit the nice formatting?


also, your ExploreCams is a great site! It would be interesting if we could set up a CI server to run over your collection of images comparing exiftool output results every time there's a new exiftool pre-release to check for regressions.

**Comment by linaspasv** [comment]
@mattsta based on my observations it will be very hard to determine when LensType should be used and when not. It's clearly good for iPhone photos but the original implementation covered 80-90% other cases correctly. It would be very nice if we could come up with a clever method to cover the rest of cases too... 

I would probably suggest to revert this pull back for now and try to work on this more. I would definitely help in testing.

**Comment by mattsta** [comment]
Yeah, we need a way to say "If lens can be retrieved from lens type hash, use lens from lens type hash; else generate composite lens ID using individual fields directly"

Based on the `Require => 'LensType'` line, I was assuming `LensType` had the full original lens information, but—surprise!—it doesn't! It's just empty.

Right now those two behaviors are conflicting because by the time we hit composite `LensID => PrintConv`, all the lens model information (and original lens ID indexing into the lens hash) isn't available anymore. Not sure why!

Also the proper value returns if we just intentionally fail the `RawConv` test by returning `undef`. It apparently falls back to using the original lens hash lookup value directly without continuing on to `PrintConv`.

It feels like the universal solution is just one or two lines of code away from working for all cases, but there's {{magic}} going on behind the scenes I can't seem to track down (where values are appearing and vanishing between different parts of the output generation pipeline flow).

**Comment by boardhead** [comment]
I need to find time to think about this in detail and run some tests myself.  This may take a few days.

**Comment by boardhead** [comment]
The complication is that there are four different Composite:LensID tags which handle different situations (see https://exiftool.org/TagNames/Composite.html).  This is messy, I know, but maybe we can patch this by moving the new code into yet another Composite:LensID tag.  I'm currently thinking of something like this (see attached file).

Maybe you two could try this out to see how it works on your test images.  I ran this through my test suite and it seems to do pretty well, but I don't have a very comprehensive LensID test suite.

[Exif.pm.zip](https://github.com/exiftool/exiftool/files/5912544/Exif.pm.zip)

**Comment by mattsta** [comment]
The update works better with the limited test files we were playing with here!

```haskell
% for f in *.jpg; do echo "-- $f"; ./exiftool $f|grep Lens; done
-- 106345359-98449e80-627d-11eb-833e-cb7a8f719da7.jpg
Lens Info                       : 75-300mm f/4.5-5.6
Lens Model                      : 75-300mm F4.5-5.6
Lens                            : 75-300mm F4.5-5.6
Lens Profile Enable             : 0
Lens Manual Distortion Amount   : 0
Lens Profile Setup              : LensDefaults
Lens ID                         : Minolta/Sony AF 75-300mm F4.5-5.6 (D)
-- P1010177-smaller.jpg
Lens                            : LUMIX G 14/F2.5
Lens Serial Number              : 01JG6061760R
Lens ID                         : LUMIX G 14mm F2.5
-- cars-smaller.jpg
Lens Info                       : 4.25-6mm f/1.8-2.4
Lens Make                       : Apple
Lens Model                      : iPhone XS Max back dual camera 4.25mm f/1.8
Lens ID                         : iPhone XS Max back dual camera 4.25mm f/1.8
```

The lens details without model names above should be able to just pass-through from the lens hash since the info is already there:
```haskell
% rg "150-600mm F5-6.3 DG OS HSM"
Nikon.pm
516:    '81 34 76 A6 38 40 4B 0E' => 'Sigma 150-600mm F5-6.3 DG OS HSM | S', #Jaap Voets
517:    '82 34 76 A6 38 40 4B 0E' => 'Sigma 150-600mm F5-6.3 DG OS HSM | C',

Sigma.pm
191:    0x740 => 'Sigma 150-600mm F5-6.3 DG OS HSM | S',
192:    0x745 => 'Sigma 150-600mm F5-6.3 DG OS HSM | C',
229:    0x6001 => 'Sigma 150-600mm F5-6.3 DG OS HSM | S', #PH (NC, fp)

Sony.pm
200:    50486 => 'Sigma 150-600mm F5-6.3 DG OS HSM | C + MC-11', #JR (015)
203:    50489 => 'Sigma 150-600mm F5-6.3 DG OS HSM | S + MC-11', #JR (014)

% rg "E PZ 16-50mm F3.5-5.6 OSS"
Sony.pm
95:    32793 => 'Sony E PZ 16-50mm F3.5-5.6 OSS',  # VX9109
```

Also worth noting these cases for *.7EF50mm f/1.8 STM* or  *EF50mm f/1.8 II* or *XC16-50mmF3.5-5.6 OIS*  where some lens string components are being both dropped and having spaces removed:
```haskell
-- searching what made: EF50mm f/1.8 II
% rg "EF 50mm f/1.8 II"
Canon.pm
162:    29 => 'Canon EF 50mm f/1.8 II',

-- searching what made: .7EF50mm f/1.8 STM
% rg "EF 50mm f/1.8 STM"
Canon.pm
554:    4156 => 'Canon EF 50mm f/1.8 STM', #42

-- searching what made: XC16-50mmF3.5-5.6 OIS (no direct match, but this was the closest?)
% rg "F3.5-5.6 OIS"
Samsung.pm
37:    2 => 'Samsung NX 18-55mm F3.5-5.6 OIS', # (also version II, ref 1)
```

Looks like there's some pre-processing string split/join behavior going on somewhere, but the original string is already okay for many instances?

**Comment by linaspasv** [comment]
```
-- searching what made: XC16-50mmF3.5-5.6 OIS (no direct match, but this was the closest?)
% rg "F3.5-5.6 OIS"
Samsung.pm
37:    2 => 'Samsung NX 18-55mm F3.5-5.6 OIS', # (also version II, ref 1)
```

this is clearly a "https://fujifilm-x.com/global/products/lenses/xc16-50mmf35-56-ois-2/"

**Comment by linaspasv** [comment]
Some of these listed strings are quite common. I have a database of 25M+ photos scanned with exiftool over several years.

**E PZ 16-50mm F3.5-5.6 OSS**
https://explorecams.com/photos/lens/e-pz-16-50mm-f3-5-5-6-oss

**for 150-600mm F5-6.3 DG OS HSM | Contemporary 015**
https://explorecams.com/photos/lens/150-600mm-f5-6-3-dg-os-hsm-contemporary-015

**for .7EF50mm f/1.8 STM**
https://explorecams.com/photos/lens/7ef50mm-f-1-8-stm

**for EF50mm f/1.8 II**
https://explorecams.com/photos/lens/ef50mm-f-1-8-ii

**for XC16-50mmF3.5-5.6 OIS**
https://explorecams.com/photos/lens/xc16-50mmf3-5-5-6-ois

**Comment by boardhead** [comment]
Adding the lens make to the name would be a whole new challenge, so I don't want to tackle that right now.  I would like to tweak the PrintConv a bit to standardize lens names with a space after "mm" but not before, and to remove spaces around any "-":

    PrintConv => '$_=$val; s/(\d)\/F/$1mm F/; s/mmF/mm F/; s/(\d) mm/${1}mm/; s/ - /-/; $_',

And after that I would be happy to make a new release if that works for you two.

**Comment by linaspasv** [comment]
@boardhead would it be possible (atleast for now) to add an additional field where we could have some sort of information about the composite LensID strategy that was used to generate the output? I am a little bit afraid to go live with these changes on my database but better have some sort of control / additional information to tweak the backend logic and track things, especially when PrintConv will change the output strings and will result into an additional number of unbranded lens strings in the database. Let me know your thoughts. Thanks.

**Comment by boardhead** [comment]
@linaspasv For the PrintConv changes, the additional information is already available by disabling the PrintConv option (either with -n, or -lensid#).  Is this helpful?

**Comment by linaspasv** [comment]
@boardhead oh I did not know about these commands. I guess I am good. Thank you!

**Comment by mattsta** [comment]
Fits all my test cases for now too 👍

Thanks for showing how to simplify the composite output by splitting into multiple conditions. I didn't realize a second condition could inhibit *and* replace a previous field at the same time.

**Comment by linaspasv** [comment]
I was just looking at the database for "Canon EF 85mm f/1.8 USM" lens and found nearly 8 exif string variations for a single lens. See an attached image: image

I just learned today that Canon EF lenses can be used on the Panasonic GH4. 3 records that start with .7, .x64, .7x were used with Panasonic cameras. I guess that is the main reason we get these differences and odd Lens IDs sometimes, maybe it even depends on camera firmware and how it outputs the lens strings... :-)

**Comment by boardhead** [comment]
> I didn't realize a second condition could inhibit and replace a previous field at the same time.

The Inhibit entry prevents generation of the current tag if any of tags in the Inhibit list exist (So LensID-2 won't be generated if Composite:LensID exists).

**Comment by boardhead** [comment]
ExifTool 12.17 with this patch is now available.

**Pull request closed without merging**
