### PR TITLE
Added parsing of video timstamps from record 6 for Insta360 timelapse videos.

### PR DESCRIPTION
**Pull request by tomfallen**
Additionally, clarified a few data types.

### CODE REVIEW

**Review by boardhead — COMMENTED** [review]
Thanks, but I think you missed adding definitions for the new tags (Exposure and VideoTimestamp) in the tag table.  I don't think either of these should have worked for you (did you test this?).  I'll include this patch but Exposure to ExposureTime since this was already defined, and add a new VideoTimeStamp tag to the table.

**Comment by tomfallen** [comment]
Thanks.  I probably did miss adding definitions to the tag tables, but it did run for me and print the info I was looking for.

I'm not actually sure what units the exposure data is in, but it does not appear to be a time, and is definitely not the actual exposure time in seconds or milliseconds.  I'm fine with it being called whatever, though.

**Comment by boardhead** [comment]
I only have one sample, and the exposure values were 0.03333, which would be a long-ish exposure for video (1/30 sec).  So if the time isn't in seconds, what is it?  If we can't figure this out, maybe it would be better to leave it as unknown like it was.  Also, I don't have a sample with the VideoTimeStamp's.  Are these in seconds?

**Comment by tomfallen** [comment]
VideoTimeStamps are milliseconds.  They only appear in timelapse videos.

I went back and checked again and think you might be correct that the exposure values are actual exposure times in seconds.

**Comment by boardhead** [comment]
Merged and released in ExifTool 12.07

**Comment by DeanZwikel** [comment]
Hi. By any chance, has there been any investigation into what data is stored in record type 5?

**Comment by boardhead** [comment]
Not by me.

**Comment by tomfallen** [comment]
I suspect that records 2 and 5 are both thumbnail images in some compressed format.

I've investigated a small amount - searching for magic strings for common formats like JPG and PNGs, and writing the entire record to disk and seeing if Exiftool would recognized it - but with no luck so far.  One possibility is that they're JPG format but missing most/all of the normal JPG headers.  Another is that they're something else entirely.

**Pull request closed without merging**
